os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8.3
script:
  - eval "$(curl -sL https://raw.githubusercontent.com/vapor-community/swift/master/ci-3.1)"
after_success:
  - eval "$(curl -sL https://raw.githubusercontent.com/vapor-community/swift/master/codecov)"
